name: Close the milestone e
on:
  create: 
    tags:
     - "**"
  push:
    tags: 
      - "**"
jobs:
  close_milestone:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Narrdin!! "
        
