name: Close the milestone e
on:
  push:
    tags: 
      - "**"
    branches:
      - refs/tags/*
jobs:
  close_milestone:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Narrdin!! "
        
