 # Sequence of patterns matched against refs/tags
on:
  push:
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - run: git fetch --prune --unshallow

      - name: Create changelogs
        id: changelogs
        uses: heineiuo/create-changelogs@master

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.FEDY_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelogs.outputs.changelog_text }}
          draft: false
          prerelease: ${{ steps.changelogs.outputs.release_type == 'prerelease' }}
