# Trigger the workflow on milestone events
on:
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.FEDY_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
      - run: echo "$OUTPUT_FILENAME"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.FEDY_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.milestone.number }}
          release_name: Release ${{ github.event.milestone.number }}
          body_path: temp_release_notes/release_file.md
          draft: false
          prerelease: false
