# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags: v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: adlerhsieh/prepare-release@v0.1.2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: 'fedysalah'
          REPO: 'fp-arrow-flux'
          IGNORE_MILESTONE_NOT_FOUND: false
