# This is a basic workflow to help you get started with Actions

name: Close the milestone
on:
  push:
    tags:
      - v**
jobs:
  close_milestone:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello bitch'
